### ISSUE TITLE
Website Update Broke Extension

### ISSUE THREAD

**Issue by Aevum11** [lazytwinkletoes/nexus-mod-image-downloader#1]
Nexus just updated their site and the extension will no longer function. It's kinda weird because as long as I do not refresh my old tabs it will still download the images just fine but if I reload the page, which causes it to show the recent changes, the extension will not work.

**Comment by Alex98ru** [comment]
Just change the line in foreground.js
  let titleDiv = document.querySelector(".game-name");
to
  let titleDiv = document.querySelector(".sr-only");

**Comment by Aevum11** [comment]
Just got around to reply. That does not work. The extension will not download images, even with that fix.

**Comment by Aevum11** [comment]
That fix works. Thank you!
